config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth" }
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :resumes
  # root "resumes#index"
  root "welcomes#index"

  get "pricing", to: "static_pages#pricing"
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  get "profile", to: "static_pages#profile"
  get "resumelist", to: "static_pages#resumelist"

  resources :resume2s
  resources :resume3s
  resources :resume4s
  resources :resume5s
  resources :resume6s
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:profile]

  def pricing
  end

  def profile
  end

  def resumelist
  end
end

app/views/static_pages/pricing.html.erb
<div class="pricing-card container">
  <h2 class="text-center my-5"> ResumeMaker Subscription Prices</h2>
  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <% @pricing = Stripe::Price.list(lookup_keys: ["resume_2Temp_300", "resume_4Temp_400", "resume_6Temp_600"], expand: ["data.product"]) %>
    <% @pricing.each do |price| %>
      <div class="col">
        <% if price.unit_amount/100 == 300 %>
          <div class="card mb-4 rounded-3 shadow-sm border-primary checkout-card">
            <div class="card-header py-3 text-white bg-primary border-primary">
              <h4 class="my-0 fw-normal">Basic</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title"><%= price.unit_amount/100 %> ₹<small class="text-muted fw-light">/<%= price.recurring.interval %></small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>2 Templates</li>
              </ul>
              <%= link_to "Checkout", checkout_create_path(price: price.id), method: :post, class:"btn btn-primary btn-lg w-100 checkout-btn", remote: true %>
            </div>
          </div>
        <% elsif price.unit_amount/100 == 400 %>
          <div class="card mb-4 rounded-3 shadow-sm border-success checkout-card">
            <div class="card-header py-3 text-white bg-success border-success">
              <h4 class="my-0 fw-normal">Pro</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title"><%= price.unit_amount/100 %> ₹<small class="text-muted fw-light">/<%= price.recurring.interval %></small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>4 Templates</li>
              </ul>
              <%= link_to "Checkout", checkout_create_path(price: price.id), method: :post, class:"btn btn-success btn-lg w-100 checkout-btn", remote: true %>
            </div>
          </div>
        <% else %>
          <div class="card mb-4 rounded-3 shadow-sm border-warning checkout-card">
            <div class="card-header py-3 text-white bg-warning border-warning">
              <h4 class="my-0 fw-normal">Premium</h4>
            </div>
            <div class="card-body">
              <h1 class="card-title pricing-card-title"><%= price.unit_amount/100 %> ₹<small class="text-muted fw-light">/<%= price.recurring.interval %></small></h1>
              <ul class="list-unstyled mt-3 mb-4">
                <li>6 Templates</li>
              </ul>
              <%= link_to "Checkout", checkout_create_path(price: price.id), method: :post, class:"btn btn-warning btn-lg w-100 checkout-btn", remote: true %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/profile.html.erb
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-12 col-xl-4">
        <div class="card" style="border-radius: 15px;">
          <div class="card-body text-center">
            <div class="mt-3 mb-4 profile-image">
              <%= image_tag("user2.png") %>
            </div>
            <h1 class="mb-2">Rutik K Patel</h1>
            <p class="text-muted mb-4">@Programmer </p>
            <p class=" mb-4">E-mail : <%= current_user.email %> </p>
            <p class=" mb-4">Stripe Customer id : <%= current_user.stripe_customer_id %> </p>
            <div class="d-flex align-items-center justify-content-around">
              <%= button_to "Billing Portal", billing_portal_create_path, class:"btn btn-primary rounded btn-lg" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-warning rounded btn-lg" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/resumelist.html.erb
<div class="resumelist-main">
  <br>
  <div class="row justify-content-around align-items-center">
    <div class="col-lg-4 col-sm-6 col-12 mb-5 ">
      <%= link_to new_resume_path do %>
        <div class="card mycard" >
          <%= image_tag("template1.png") %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-4 col-sm-6 col-12 mb-5 ">
      <%= link_to new_resume2_path do %>
        <div class="card mycard">
          <%= image_tag("template2.png") %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-4 col-sm-6 col-12 mb-5 temp3">
      <%= link_to new_resume3_path do %>
        <div class="card mycard" >
          <%= image_tag("template3.png") %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-4 col-sm-6 col-12 mb-5 ">
      <%= link_to new_resume4_path do %>
        <div class="card mycard" >
          <%= image_tag("template4.png") %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-4 col-sm-6 col-12 mb-5 ">
      <%= link_to new_resume5_path do %>
        <div class="card mycard">
          <%= image_tag("template5.png") %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-4 col-sm-6 col-12 mb-5 ">
      <%= link_to new_resume6_path do %>
        <div class="card mycard" >
          <%= image_tag("template6.png") %>
        </div>
      <% end %>
    </div>
  </div>
</div>