config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth" }
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :resumes
  # root "resumes#index"
  root "welcomes#index"

  get "pricing", to: "static_pages#pricing"
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  get "profile", to: "static_pages#profile"
  get "resumelist", to: "static_pages#resumelist"

  resources :resume2s
  resources :resume3s
  resources :resume4s
  resources :resume5s
  resources :resume6s
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <footer class="text-center text-lg-start bg-light text-muted">
    <section class="pt-5">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fa fa-th-large me-3"></i>RESUME MAKER
            </h6>
            <p>
              Save time by using the simplest online resume maker. Create a strong Resume in just a few minutes to land the job of your dreams.
            </p>
          </div>
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Resumes
            </h6>
            <p>
              <a href="#!" class="text-reset">Resume 1</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Resume 2</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Resume 3</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Resume 4</a>
            </p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">How it works?</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Testinomals</a>
            </p>
            <p>
              <a href="#!" class="text-reset">About</a>
            </p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              NewsLetter
            </h6>
            <div class="form-outline mb-4">
              <input type="email" id="form5Example25" class="form-control" placeholder="Enter Email Here..." />
            </div>
            <%= button_to "Subscribe", root_path, class:"btn btn-success" %>
          </div>
        </section>
        <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
          © 2022 Copyright - Made by 
          <a class="text-reset fw-bold" href="https://github.com/rutikpatel20">Rutik Patel</a>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <a href="/" class="me-2"><%= image_tag("R_logo.png") %></a>
      <span class=""> RESUMEMAKER</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/pricing">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#steps">How it Works?</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#testinomals">Testinomals</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#">About</a>
        </li>
        <li class="nav-item">
          <%= link_to "ResumeList", resumelist_path, class:"nav-link active active" %>
        </li>
      </ul>
      <div class="d-flex align-items-center">
        <% if signed_in? %>
          <%= button_to "User Profile", profile_path, method: :get, class:"btn btn-success rounded-pill" %>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class:"btn-danger border-0 rounded-pill shadow px-3 py-2 m-2 text-decoration-none" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class:"btn-success border-0 rounded-pill shadow px-3 py-2 m-2 text-decoration-none" %>
          <%= link_to "Register", new_user_registration_path, class:"btn-primary border-0 rounded-pill shadow px-3 py-2 my-2 text-decoration-none" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResumeMakerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Stripe API -->
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Favicon -->
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <!-- FONTS -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <!--Bootstrap CDN  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- FontAwesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div class="content">
      <%= render 'layouts/navbar' %>
      <% if notice %>
        <p class="alert alert-success text-center"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger text-center"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>